spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: sms-service
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**
server:
  port: 8080
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
